//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnSharp.Windows.Updater.SharpPack {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PackSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PackSettings defaultInstance = ((PackSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PackSettings())));
        
        public static PackSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QueryFilesVersionFromReleaseServer {
            get {
                return ((bool)(this["QueryFilesVersionFromReleaseServer"]));
            }
            set {
                this["QueryFilesVersionFromReleaseServer"] = value;
            }
        }
    }
}
